-- Adding books from the browser: an upload permission and the URL import queue.
--
-- can_upload is a per-account flag rather than a role, because "may add books"
-- and "may administer the server" are different powers: a household wants the
-- second reader to be able to drop an EPUB in without also handing them the
-- user list. Administrators are always allowed and the restricted role never
-- is, so the column only decides the case in between. It defaults to 0, so an
-- upgrade grants nobody anything they did not have yesterday.
ALTER TABLE users ADD COLUMN can_upload INTEGER NOT NULL DEFAULT 0;

-- One row per URL import. The work happens outside the request that created
-- it, so the row is the only thing the client and the worker share: the client
-- polls it, the worker advances it, and a cancel deletes it - which the worker
-- notices between steps and stops.
CREATE TABLE import_jobs (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    library_id BIGINT NOT NULL REFERENCES libraries(id) ON DELETE CASCADE,
    url        TEXT NOT NULL,
    status     TEXT NOT NULL CHECK (status IN ('queued', 'running', 'done', 'failed')),
    message    TEXT NOT NULL DEFAULT '',
    item_id    BIGINT REFERENCES items(id) ON DELETE SET NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE INDEX idx_import_jobs_user ON import_jobs(user_id, id);
CREATE INDEX idx_import_jobs_status ON import_jobs(status, id);
