package store

import (
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The two backends are kept honest by convention rather than by a rewriter, so
// the conventions are tested. Without this file the usual failure mode is a
// query that works perfectly on a developer's SQLite and only fails on the
// Postgres deployment nobody can reproduce locally.

// Both migration directories must hold the same steps under the same names:
// the recorded version is the bare filename, so a step that exists on one side
// only would leave the two schemas silently divergent.
func TestMigrationDirectoriesMatch(t *testing.T) {
	sqliteNames, err := migrationNames(sqliteDialect{}.migrationsDir())
	if err != nil {
		t.Fatalf("read sqlite migrations: %v", err)
	}
	pgNames, err := migrationNames(postgresDialect{}.migrationsDir())
	if err != nil {
		t.Fatalf("read postgres migrations: %v", err)
	}
	if len(sqliteNames) == 0 {
		t.Fatal("no migrations are embedded")
	}
	if strings.Join(sqliteNames, ",") != strings.Join(pgNames, ",") {
		t.Errorf("migration sets differ:\n  sqlite:   %v\n  postgres: %v", sqliteNames, pgNames)
	}
}

// Postgres migrations must not carry SQLite-only syntax. Each of these has
// bitten a real project: AUTOINCREMENT and the rowid alias are silently valid
// SQLite that Postgres rejects outright, datetime() and INSERT OR do not exist,
// and a "?" in DDL means the file was copied without being translated.
func TestPostgresMigrationsHaveNoSQLiteSyntax(t *testing.T) {
	banned := []struct{ needle, why string }{
		{"autoincrement", "AUTOINCREMENT is SQLite-only; use GENERATED BY DEFAULT AS IDENTITY"},
		{"datetime(", "datetime() is SQLite-only; timestamps are written by the application"},
		{"insert or ", "INSERT OR ... is SQLite-only; use ON CONFLICT"},
		{"?", "a \"?\" placeholder in DDL means the file was not translated"},
		{"collate nocase", "COLLATE NOCASE is SQLite-only; fold with lower()"},
		{"pragma", "PRAGMA is SQLite-only"},
		{"blob", "BLOB is SQLite-only; use BYTEA"},
		{"integer primary key", "a rowid alias is SQLite-only; use BIGINT GENERATED BY DEFAULT AS IDENTITY"},
		{" real", "REAL is a 4-byte float in Postgres; use DOUBLE PRECISION"},
	}
	forEachMigration(t, postgresDialect{}.migrationsDir(), func(name, body string) {
		// setup_state and settings are single-row tables carrying an explicit
		// id rather than a generated one, so their "INTEGER PRIMARY KEY
		// CHECK (id = 1)" is deliberate and means the same thing to both
		// backends. Everything else spelled that way is a missed translation.
		lower := strings.ReplaceAll(strings.ToLower(body), "integer primary key check (id = 1)", "")
		for _, b := range banned {
			if strings.Contains(lower, b.needle) {
				t.Errorf("%s contains %q: %s", name, strings.TrimSpace(b.needle), b.why)
			}
		}
	})
}

// SQLite migrations must not carry Postgres-only syntax either, for the same
// reason in the other direction.
func TestSQLiteMigrationsHaveNoPostgresSyntax(t *testing.T) {
	banned := []string{
		"generated by default as identity",
		"bytea",
		"double precision",
		"now()",
		"bigserial",
		"$1",
	}
	forEachMigration(t, sqliteDialect{}.migrationsDir(), func(name, body string) {
		lower := strings.ToLower(body)
		for _, needle := range banned {
			if strings.Contains(lower, needle) {
				t.Errorf("%s contains Postgres-only %q", name, needle)
			}
		}
	})
}

// The Go sources outside this package must not reach for SQLite-only SQL or
// for LastInsertId, which the Postgres driver cannot answer.
func TestGoSourcesAreDialectNeutral(t *testing.T) {
	banned := []struct{ needle, why string }{
		{"COLLATE NOCASE", "SQLite-only collation; fold both sides with lower() instead"},
		{"INSERT OR ", "SQLite-only; use ON CONFLICT ... DO NOTHING / DO UPDATE"},
		{"LastInsertId", "not available on Postgres; use InsertReturningID"},
		{"datetime('now')", "SQLite-only; timestamps come from store.Now()"},
		{"sqlite_master", "SQLite-only catalog table"},
		{"PRAGMA ", "SQLite-only"},
	}

	root := repoRoot(t)
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			switch d.Name() {
			case ".git", "web", "bin":
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") {
			return nil
		}
		// This package is where the dialect differences are allowed to exist,
		// and where they are named in comments and tests.
		if filepath.Dir(path) == filepath.Join(root, "internal", "store") {
			return nil
		}
		body, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		for _, line := range strings.Split(string(body), "\n") {
			trimmed := strings.TrimSpace(line)
			// Comments explaining why a construct is avoided are not uses.
			if strings.HasPrefix(trimmed, "//") {
				continue
			}
			for _, b := range banned {
				if strings.Contains(line, b.needle) {
					rel, _ := filepath.Rel(root, path)
					t.Errorf("%s uses %q: %s", rel, b.needle, b.why)
				}
			}
		}
		return nil
	})
	if err != nil {
		t.Fatalf("walk sources: %v", err)
	}
}

func forEachMigration(t *testing.T, dir string, check func(name, body string)) {
	t.Helper()
	names, err := migrationNames(dir)
	if err != nil {
		t.Fatalf("read %s: %v", dir, err)
	}
	for _, name := range names {
		body, err := migrationsFS.ReadFile(dir + "/" + name)
		if err != nil {
			t.Fatalf("read %s/%s: %v", dir, name, err)
		}
		check(dir+"/"+name, stripComments(string(body)))
	}
}

// stripComments removes "--" line comments so prose in a migration header
// cannot trip the lint.
func stripComments(body string) string {
	var b strings.Builder
	for _, line := range strings.Split(body, "\n") {
		if i := strings.Index(line, "--"); i >= 0 {
			line = line[:i]
		}
		b.WriteString(line)
		b.WriteByte('\n')
	}
	return b.String()
}

// repoRoot walks up from the test's working directory to the module root.
func repoRoot(t *testing.T) string {
	t.Helper()
	dir, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatal("could not find the module root")
		}
		dir = parent
	}
}

func TestPostgresRebind(t *testing.T) {
	d := postgresDialect{}
	cases := []struct{ in, want string }{
		{"SELECT 1", "SELECT 1"},
		{"WHERE a = ? AND b = ?", "WHERE a = $1 AND b = $2"},
		{"INSERT INTO t (a, b, c) VALUES (?, ?, ?)", "INSERT INTO t (a, b, c) VALUES ($1, $2, $3)"},
		// A "?" inside a string literal is data, not a parameter.
		{"WHERE note = 'huh?' AND id = ?", "WHERE note = 'huh?' AND id = $1"},
		// The search predicate: an ESCAPE clause between two placeholders.
		{`lower(a) LIKE ? ESCAPE '\' OR lower(b) LIKE ? ESCAPE '\'`,
			`lower(a) LIKE $1 ESCAPE '\' OR lower(b) LIKE $2 ESCAPE '\'`},
	}
	for _, c := range cases {
		if got := d.Rebind(c.in); got != c.want {
			t.Errorf("Rebind(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}

func TestSQLiteRebindIsANoOp(t *testing.T) {
	if got := (sqliteDialect{}).Rebind("a = ? AND b = ?"); got != "a = ? AND b = ?" {
		t.Errorf("sqlite Rebind changed the query: %q", got)
	}
}

func TestRedactDSN(t *testing.T) {
	cases := []struct{ in, want string }{
		{"", ""},
		{"postgres://bookshelf:hunter2@db.example.com:5432/books", "postgres://bookshelf:***@db.example.com:5432/books"},
		{"postgres://bookshelf:hunter2@db.example.com:5432/books?sslmode=require", "postgres://bookshelf:***@db.example.com:5432/books?..."},
		{"postgres://db.example.com:5432/books", "postgres://db.example.com:5432/books"},
		{"host=db.example.com password=hunter2", "(redacted)"},
	}
	for _, c := range cases {
		if got := RedactDSN(c.in); got != c.want {
			t.Errorf("RedactDSN(%q) = %q, want %q", c.in, got, c.want)
		}
		if strings.Contains(RedactDSN(c.in), "hunter2") {
			t.Errorf("RedactDSN(%q) leaked the password", c.in)
		}
	}
}
